import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();


  return (
    <div >
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello World</h1>
      <button onClick={()=> router.push('/news/')}>click me</button>
    </div>
  );


}
