import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1  className={styles.title}>Home</h1>
      <p  className={styles.text}>
        the quick brown fox jumps over the lazy dog. the quick brown fox jumps
        over the lazy dog.the quick brown fox jumps over the lazy dog{" "}
      </p>
      <p  className={styles.text}>
        the quick brown fox jumps over the lazy dog. the quick brown fox jumps
        over the lazy dog.the quick brown fox jumps over the lazy dog{" "}
      </p>
     
      <Link href="/names">
        <a  className={styles.btn}>Name List:</a>
      </Link>
    </>
  );
}
